package com.dockeriq.service.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.index.Indexed;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

import java.time.LocalDateTime;

@Data
@Document(collection = "users")
public class User {
    
    @Id
    private String id; // ID is optional now, it can be autogenerated by MongoDB.
    
    @NotBlank(message = "Email is required")
    @Email(message = "Email should be valid")
    @Indexed(unique = true)
    private String email; // Email is now unique and primary.
    
    private String password;

    @NotBlank(message = "First name is required")
    private String firstName;
    
    @NotBlank(message = "Last name is required")
    private String lastName;

    @NotBlank(message = "role should not be empty")
    private String role;

    private Boolean active;
    
    private Boolean passwordReset;
    
    private LocalDateTime createdAt;
    
    private LocalDateTime updatedAt;
    
}
