package com.dockeriq.service.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import org.springframework.data.mongodb.core.index.Indexed;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

import java.time.LocalDateTime;

@Data
@Document(collection = "users")
public class User {
    
    @Id
    private String id; // ID is optional now, it can be autogenerated by MongoDB.
    
    @Indexed(unique = true)
    private String email; // Email is now unique and primary.
    @NotBlank(message = "Role is required")
    private String role;
    @NotBlank(message = "First name is required")
    private String firstName;
    @NotBlank(message = "Last name is required")
    private String lastName;
    @NotBlank(message = "address is required")
    private String address;
    @NotBlank(message = "phoneNumber is required")
    private String phoneNumber;
    private Boolean active;
    private String password;
    private Boolean passwordReset;
    private String createdBy;
    private String updatedBy;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    
}
