spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/dockeriq
  
  # Disable MongoDB query logging to hide sensitive data
  jpa:
    show-sql: false
  
  # Disable MongoDB query logging
  mongodb:
    auto-index-creation: false
  
  # File upload configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}
  
  # Security configuration
  security:
    user:
      name: admin
      password: admin

# JWT Configuration
jwt:
  secret: your-secret-key-here-make-it-long-and-secure-in-production
  expiration: 86400000

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api

# Logging Configuration - Hide sensitive information
logging:
  level:
    com.dockeriq.service: INFO
    org.springframework.security: INFO
    org.springframework.data.mongodb.core.MongoTemplate: WARN
    org.springframework.data.mongodb.core.MongoDbUtils: WARN
    org.mongodb.driver: WARN
    org.springframework.web: INFO
    root: WARN
    # Completely disable MongoDB query logging
    org.springframework.data.mongodb: WARN
    org.springframework.data.mongodb.core.query: WARN
  
  # Disable MongoDB query logging
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  
  # Hide sensitive data in logs
  file:
    name: logs/application.log

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
