spring:
  data:
    mongodb:
      uri: mongodb+srv://katarideepak_db_user:VRCpUhl5KiYvbWxD@cluster0.5jfwqxr.mongodb.net/DockerIQ?retryWrites=true&w=majority&appName=Cluster0&ssl=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.dockeriq.service: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8080
