spring:
  data:
    mongodb:
      uri: mongodb://dockeriq:dockeriq123@docdb.cluster-ckhmkioayf8x.us-east-1.docdb.amazonaws.com:27017/?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  
  # File upload configuration for development
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}

logging:
  level:
    com.dockeriq.service: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.web: DEBUG

server:
  port: 8080
